name: Desplegar Radio Satelital

on:
  # Se activa cuando subes cambios a la rama 'main'
  push:
    branches: ["main"]
  # Permite ejecutarlo manualmente desde la pestaÃ±a Actions
  workflow_dispatch:

# Permisos necesarios para que el bot pueda escribir en tu web
permissions:
  contents: read
  pages: write
  id-token: write

# Evita que se solapen dos actualizaciones al mismo tiempo
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Trabajo Ãºnico de despliegue
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Descargar tu cÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: ğŸ“¦ Empaquetar archivos (HTML, CSS, JS)
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: ğŸš€ Publicar en Internet
        id: deployment
        uses: actions/deploy-pages@v4
        
